### PR TITLE
Bug/gesture bounds

### LINKED ISSUE #137: holding jump button will trigger player to move forward
- Issue with gesture recogniser bounds in local multiplayer

### PR DESCRIPTION
**Pull request by ruihan00**
Previously, holding down jump button will trigger move forward. Long pressing on right edge of screen will trigger move forward

Fix gesture control to check if long presses are in any action buttons,

fix issue where the ignore area rect on local multiplayer is smaller than expected, I think this is because the frame size is not inverted when the rotation is 90.

fix issue where long press gesture on some areas of screen don't move joystick

closes #137

### CODE REVIEW

File: star-dash/star-dash/Rendering/PlayerView/ControlView.swift [hunk 1]
```diff
@@ -14,12 +14,14 @@ class ControlView: UIView, UIGestureRecognizerDelegate {
...
     var controlViewDelegate: ControlViewDelegate?
-
+    var jumpButton: UIButton?
+    var hookButton: UIButton?
     func setupSubviews() {
         setupMovementControls()
         setupActionControls()
         setupGestureRecognizers()
     }
+    var rotatedBy: CGFloat = 0
```
Comment (Junyi00) [inline star-dash/star-dash/Rendering/PlayerView/ControlView.swift:24]: the declaration should come before the method

Comment (Junyi00) [inline star-dash/star-dash/Rendering/PlayerView/ControlView.swift:24]: This variable declaration should come before our methods like `setupSubviews`

File: star-dash/star-dash/Rendering/PlayerView/PlayerView.swift [hunk 2]
```diff
@@ -35,6 +35,7 @@ class PlayerView {
         superview.addSubview(self.minimapView)
 
         self.controlView = ControlView(frame: superview.bounds, rotatedBy: rotation)
+        controlView.rotatedBy = rotation
```
Comment (Junyi00) [inline star-dash/star-dash/Rendering/PlayerView/PlayerView.swift:38]: This could be initialised in `ControlView` itself during its init

**Review by Junyi00 — CHANGES_REQUESTED** [review]

File: star-dash/star-dash/Rendering/PlayerView/PlayerView.swift (hunk 2 above)
Comment (ruihan00) [reply star-dash/star-dash/Rendering/PlayerView/PlayerView.swift]: how to do this? overriding UIView's init would cause a error where its not possible to override
