### PR TITLE
fix player death

### LINKED ISSUE #128: Player can die in the air
# Description
Ocassionally, the player dies in the air. After standing up, it gets stuck in that position in the air for a while before dropping to the ground and becomes movable.

### PR DESCRIPTION
**Pull request by HoJunHao2000**
Resolves #128

# Fix
1) Players no longer die in the sky
- When players die now they will fall to ground

2) Players cannot jump/hook after dying
- Previously there was a bug where the player might die with jump component, resulting in a scenario where on respawn he is unable to jump/hook.

### CODE REVIEW

File: star-dash/star-dash/GameEngine/Systems/Complex/DeathSystem.swift [hunk 1]
```diff
@@ -83,9 +83,12 @@ class DeathSystem: System {
             return
         }
 
+        if let jumpComponent = entityManager.component(ofType: JumpComponent.self, of: event.playerId) {
```
Comment (Junyi00) [inline star-dash/star-dash/GameEngine/Systems/Complex/DeathSystem.swift:86]: Should the responsibility of removing jumpComponent be from the JumpModule in MovementSystem instead? Or maybe we could do something like MovementSystem.cancelAllMovement(for: entityId)

Comment (HoJunHao2000) [reply star-dash/star-dash/GameEngine/Systems/Complex/DeathSystem.swift]: ok. moved logic to MovementSystem. DeathSystem now calls .cancelAllMovement(for: entityId)

File: star-dash/star-dash/GameEngine/Systems/Complex/Movement/FlyingModule.swift [hunk 2]
```diff
@@ -112,6 +112,18 @@ class FlyingModule: MovementModule {
         spriteSystem.setSize(of: entityId, to: PhysicsConstants.Dimensions.plane)
     }
 
+    func cancelMovement(for entityId: EntityId) {
```
Comment (Junyi00) [inline star-dash/star-dash/GameEngine/Systems/Complex/Movement/FlyingModule.swift:115]: i think its better to just call cancelFlying(for: entityId) to avoid avoid eduplication

**Review by Junyi00 — CHANGES_REQUESTED** [review]

File: star-dash/star-dash/GameEngine/Systems/Complex/Movement/FlyingModule.swift (hunk 2 above)
Comment (HoJunHao2000) [reply star-dash/star-dash/GameEngine/Systems/Complex/Movement/FlyingModule.swift:115]: The problem with that is that it also calls will also call endAnimation which for some reason causes a delay before the dying animation starts. Same for movement.

To resolve it I added an endAnimation flag.

**Review by Junyi00 — APPROVED** [review]
